### ISSUE TITLE
ARK-28 Nginx HTTP 2.0 적용

### ISSUE THREAD

**Issue by shirohoo** [TEAM-ARK/sprout-backend#159]
[![ARK-28](https://badgen.net/badge/JIRA/ARK-28/0052CC)](https://ark-learn-back.atlassian.net/browse/ARK-28?atlOrigin=eyJpIjoiZTI5OWEzYjYwMGZkNDhjYjhhMDEyYjJlYjFiY2NkZTUiLCJwIjoiaiJ9) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=Ark-inflearn&utm_campaign=badge_info)

**Comment by MinChul-Son** [comment]
`HTTP/2.0` 적용완료!!
