### ISSUE TITLE
ARK-35 로그 컨벤션 의논

### ISSUE THREAD

**Issue by shirohoo** [TEAM-ARK/sprout-backend#173]
현재 로그에 대한 컨벤션이 전무함.

- 로그 포맷 필요
- 로그 기록 방법 필요

# 🙌 제안

- 현재 로그
![image](https://user-images.githubusercontent.com/71188307/142183461-2ab170fc-f751-4e1a-a11f-16f60751a1b1.png)

- 포맷
  - --{이모지}> [{메소드명}]{공백}{간략한 설명}{공백}{(옵셔널)파라미터 키:파라미터 값}

- 예시
```shell
[2021-11-17 19:26:45.263] INFO  http-nio-8080-exec-2 c.a.s.s.MemberService - --✅> [signUp] Sign-up request. email: 5271597125@email.com
```

**Comment by MinChul-Son** [comment]
제안하신 포멧 깔끔한 것 같습니다.

예외가 발생할 때는 ❌ 이런 이모지 사용하면 될 듯하네요.

**Comment by shirohoo** [comment]
반대없나요?
그럼 별도의 로깅용 유틸클래스를 만들겠습니다.

**Comment by shirohoo** [comment]
#178
